### ISSUE TITLE
Quiz answer 9 is wrong

### ISSUE THREAD

**Issue by p-himik** [cosmologicon/pywat#11]
It is possible:

``` python
>>> x, y = '', 0 * 1e400
>>> sum(0 * x, y) == y
False
```

**Comment by peter50216** [comment]
https://github.com/cosmologicon/pywat/blob/master/quiz.md#details-and-scope

> In particular, the following are out of scope, and are not valid as missing values:
> - `float`s and unicode, which have enough edge cases in any language. This means that `nan` and `inf` are also out of scope. Strings, if they appear, only have ascii characters.
