### ISSUE TITLE
Add old behaviour for datedatime.time

### ISSUE THREAD

**Issue by danieldiekmeier** [cosmologicon/pywat#12]
Maybe this could also be a wat?

> Before Python 3.5, a `datetime.time` object was considered to be `False` if it represented midnight in UTC. This behavior was considered obscure and error-prone and has been removed in Python 3.5.

Source: https://docs.python.org/3.5/whatsnew/3.5.html#changes-in-the-python-api

**Comment by ogroleg** [comment]
I'll send pull request with that example at evening

**Comment by millerjs** [comment]
:+1:

**Comment by cosmologicon** [comment]
I agree that's pretty surprising behavior.

So far I'm trying to stick to only wats that work in the latest version of Python. It's on my TODO list to make a "legacy" wat page, or something like it. I'll definitely keep this one in mind.
