### ISSUE TITLE
Type mixing wat is not a wat

### ISSUE THREAD

**Issue by dmytrokyrychuk** [cosmologicon/pywat#16]
Sorry to bother you, but there is no type mixing here:

```
>>> int(2 * 3)
6
>>> int(2 * '3')
33
>>> int('2' * 3)
222
```

`3 * '2'` is a shorthand for `'2' + '2' + '2'`:

```
>>> 3 * '2'
'222'
>>> '2' + '2' + '2'
'222'
```

You can't actually mix types in Python like you do in PHP. This is a magic type mixing:

``` php
$foo = "0";  // $foo is a string
$foo += 2;   // $foo is now an integer (2)
```

This is not:

```
>>> foo = '0'
>>> foo += 2
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: Can't convert 'int' object to str implicitly
```

There is no implicit str<->int type conversion in Python. When you do `int('222')` you get integer 222, which is exactly what int(str) intended to do.

It's not so confusing when you write it in more than one line:

```
>>> times = 4
>>> substring = '5'
>>> full_string = substring * times
>>> integer = int(full_string)
>>> integer
5555
```

I think this "wat" is not "wat enaugh", so it should be removed.

Thank you.

**Comment by ogroleg** [comment]
:+1:

**Comment by dougblack** [comment]
:+1:

**Comment by glasslion** [comment]
:+1:

**Comment by ogroleg** [comment]
:+1:

**Comment by cosmologicon** [comment]
Cool, thanks for the feedback. I've heard this before, so you may be absolutely right. Can you explain why you think that `"1" + 2` is type mixing but `"1" * 2` is not?

To be clear, even if `"1" * 2` is not implicit type conversion, implicit type conversion does exist in Python. You agree that `1 + 2.0` involves implicit type conversion, right?

**Comment by dmytrokyrychuk** [comment]
`"1" + 2` is type mixing (in PHP), because string `"1"` is being implicitly converted to integer `1` and then the sum of integer `1` and integer `2` calculated. `"1" + 2` in Python raises TypeError, because you can't add a string to an integer, unless you explicitly convert an integer to a string (to perform string, or string to an integer (to perform.

I am not sure about `1 + 2.0`. The result of this expression will be a type of float, which is simply the most precise type of two involved into the expression. I don't see anything unusual, unexpected or unpredictable here. I am pretty sure that Python supports arithmetics operations between integers and floats natively, just like all programming languages I know.

Python is strongly typed language. Python interpreter will not convert anything to another type, unless you instruct it to do so.

**Comment by cosmologicon** [comment]
Python does convert implicitly in several cases. `any([x])` converts `x` to `bool`, even though you never explicitly say `bool(x)`. If `x` is a float, then `x * 1j` converts it to a complex before performing the multiplication. `True + False` converts the bools to ints before doing the addition. `1 ** -1` converts the ints to floats. In Python 3, so does `1 / 1`.

I agree that Python does _less_ implicit conversion than PHP, but it doesn't do none.

> Python supports arithmetics operations between integers and floats natively, just like all programming languages I know.

Haskell and GLSL are two languages that do not. They require explicit conversion.

**Comment by dmytrokyrychuk** [comment]
>  `any([x])` converts `x` to `bool`

Nope. See the [source code](https://github.com/python/cpython/blob/master/Python/bltinmodule.c#L328). It performs  [Truth Value Testing](https://docs.python.org/3/library/stdtypes.html#truth), but does not actually convert objects to bool.

> If x is a float, then x \* 1j converts it to a complex before performing the multiplication.

This one seems to be correct. Here is what I found: [click](https://github.com/python/cpython/blob/master/Objects/complexobject.c#L471). Apparently, everything is converted to a complex during operations with complex numbers.

> `True + False` converts the bools to ints

Bools are ints from the begining:

``` python
>>> isinstance(True, int)
True
```

Thus, `True + False` is effectively the same as `1 + 0`. There is similar issue with `**` (power) operator at #18.

> I agree that Python does less implicit conversion than PHP, but it doesn't do none.

Right. Python does type conversion in case it is necessary. Like conversions to more precise number types (int to floats, floats to complex). Python won't silently convert a string to a number only because it contains digits exclusively. There is even special exception raised when (quote from docs):

> an operation or function is applied to an object of inappropriate type

[TypeError](https://docs.python.org/3/library/exceptions.html#TypeError)

> Haskell and GLSL are two languages that do not. They require explicit conversion.

Didn't know that.

**Comment by cosmologicon** [comment]
> Nope. See the source code. It performs Truth Value Testing, but does not actually convert objects to bool.

[The conversion happens on line 1245 in PyObject_IsTrue](https://github.com/python/cpython/blob/master/Objects/object.c#L1245).

> Right. Python does type conversion in case it is necessary.

Well, this is assuming one definition of "necessary", which is subjective. Maybe you think it's necessary to be able to multiply bools and floats without any explicit type conversion, and that's fine, but you would agree that someone could reasonably think otherwise, right?

**Comment by dmytrokyrychuk** [comment]
> The conversion happens on line 1245 in PyObject_IsTrue.

You're right.

**Comment by cosmologicon** [comment]
FWIW I do agree with the main point of the initial post that this is not "wat enough", even though I don't agree 100% on the specifics. I largely agree in a lot of ways, though. I've gone ahead and removed this one. Thanks for the feedback!
