### ISSUE TITLE
Converting to a string and back wat is not a wat

### ISSUE THREAD

**Issue by dmytrokyrychuk** [cosmologicon/pywat#17]
String is considered false when it is empty, so as other sequences (lists, tuples, sets, etc.). It's described in [right here](https://docs.python.org/3/library/stdtypes.html#truth-value-testing). `str(False)` is `'False'`. `'False'` is non-empty string, so `bool('False')` is `True`, same as `bool('any other non-empty string')`. Seems reasonable to me.

**Comment by ogroleg** [comment]
what do you think about adding something like that?

```
>>> False==0
True
>>> str(False)==str(0)
False
```

**Comment by dmytrokyrychuk** [comment]
It is expected that string representations of two different objects of two different types are different. It would've been worth adding if there was a place for

```
>>> str(bool(False)) == str(bool(0))
False
```

But the correct result is:

```
>>> str(bool(False)) == str(bool(0))
True
```

So personally I do not think it should be added.

**Comment by ogroleg** [comment]
thank you for detailed reply

**Comment by cosmologicon** [comment]
Yeah I agree this is a little too straightforward. I've removed it. Thanks for the feedback!
