### ISSUE TITLE
All NaNs are unequal, but some are more unequal than others

### ISSUE THREAD

**Issue by cdyson37** [cosmologicon/pywat#22]
Suggestion for a wat:

```
nan = float("nan")
print (nan == nan)                      # False
print ({1 : nan} == {1 : nan})          # True
print ({1 : nan} == {1 : float("nan")}) # False
```

**Comment by cosmologicon** [comment]
That's great. Looks like it works for lists too. I added it to the section on NaN-related wats. Thanks!

**Comment by cdyson37** [comment]
I love it! Could possibly provide a hint as to why we have this behaviour by pointing out that "x is x" but "x != x" (and it's the internal assumption that the former implies the latter that's the problem). But that might detract from the beauty of the wat :)
EDIT: You did that already in explanation.md - ignore me!
