### ISSUE TITLE
Out of scope? Copy/pasteable functions in standard library... documentation!

### ISSUE THREAD

**Issue by fxkr** [cosmologicon/pywat#3]
The standard library contains copy/pasteable functions in the comments, instead of just including them in the standard library. wat?

https://docs.python.org/3/library/itertools.html#itertools-recipes

Same for unicode support in the csv module, but maybe not fair since thats fixed in Python 3. Here goes anyway:

https://docs.python.org/2/library/csv.html

Not sure if these are out of scope - they're not in the language itself, but the standard library is an important part.

**Comment by cosmologicon** [comment]
Those are pretty good points. I never realized those gaps. But yeah I tend to think those are a little out of scope here. I'm mostly including things that are the result of deliberate design decisions.

It's good that they got around to csv unicode support in Python 3. Hopefully those recipes will be added in eventually too.

Thanks!
