### ISSUE TITLE
Converse implication operator

### ISSUE THREAD

**Issue by shazow** [cosmologicon/pywat#5]
Right now there's a section titled:

> The undocumented [converse implication](https://en.wikipedia.org/wiki/Converse_implication) operator

In case it helps clarify things, I feel it makes a lot more sense if you think of False and True implemented as 0 and 1 underneath, and *\* is a power operator.

```
>>> True == 1
True
>>> False == 0
True
```

```
>>> 0 ** 0 == True
True
>>> 0 ** 1 == False
True
>>> 1 ** 0 == True
True
>>> 1 ** 1 == True
True
```

Whether that is in and of itself a wat is up to you. :)

**Comment by daneah** [comment]
I was intent on pointing this out for the same reasons. I personally did not consider it a wat. I think calling it a converse implication operator falsely implies that Python intentionally provides it for that use.

**Comment by cosmologicon** [comment]
I've added this information to the explanations page. Thanks for the feedback!
