### ISSUE TITLE
Quiz answer 7 is wrong

### ISSUE THREAD

**Issue by vickenty** [cosmologicon/pywat#8]
```
>>> x = (i for i in range(10))
>>> len(set(list(x))) == len(list(set(x)))
False
```

**Comment by peter50216** [comment]
https://github.com/cosmologicon/pywat/blob/master/quiz.md#details-and-scope

> In particular, the following are out of scope, and are not valid as missing values:
> - anything that changes value just by inspecting it or iterating over it (iterators and generators)
